// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmI_oeuMo9GPGlVrGcYNkj5Cflmb_S4AQ',
    appId: '1:237603014133:web:4aa579966e99e210e38cbc',
    messagingSenderId: '237603014133',
    projectId: 'mychatapp-32423',
    authDomain: 'mychatapp-32423.firebaseapp.com',
    storageBucket: 'mychatapp-32423.appspot.com',
    measurementId: 'G-44VK5DGMP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVkaAFhRW4p_7V9tcQz2FVuUGZ31rQEeE',
    appId: '1:237603014133:android:4a876086f548c7d2e38cbc',
    messagingSenderId: '237603014133',
    projectId: 'mychatapp-32423',
    storageBucket: 'mychatapp-32423.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuf4-_ZPU-NACFYwnHeWAHvR-KSJiYl8g',
    appId: '1:237603014133:ios:96092fc0a736deb3e38cbc',
    messagingSenderId: '237603014133',
    projectId: 'mychatapp-32423',
    storageBucket: 'mychatapp-32423.appspot.com',
    iosClientId: '237603014133-ec1g96tn7m1bvsp3am74qbqlvrpslfbt.apps.googleusercontent.com',
    iosBundleId: 'com.sangvaleap.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuf4-_ZPU-NACFYwnHeWAHvR-KSJiYl8g',
    appId: '1:237603014133:ios:292ce7b9e8817b80e38cbc',
    messagingSenderId: '237603014133',
    projectId: 'mychatapp-32423',
    storageBucket: 'mychatapp-32423.appspot.com',
    iosClientId: '237603014133-dj3vanksl76k48ee52b5de83gbdm9c1s.apps.googleusercontent.com',
    iosBundleId: 'com.sangvaleap.chatApp',
  );
}
