name: Chat App iOS CI/CD

on:
  workflow_dispatch:

env:
  FLUTTER_CHANNEL: 'stable'
  FLUTTER_VERSION: '3.16.8'
  APP_BUNDLE_ID: 'com.sangvaleap.chatapp'
  PATH_TO_IPA: 'build/ios/ipa/com.sangvaleap.chatapp.ipa'

jobs:
  ci-cd:
    name: iOS CI/CD
    runs-on: macos-latest
    timeout-minutes: 30
    steps:  
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: ${{ env.FLUTTER_CHANNEL }}
        flutter-version: ${{ env.FLUTTER_VERSION }}

    - name: Install dependencies
      run: flutter pub get
      
    - name: Generate localization files
      run: flutter gen-l10n
    
    # - name: Set up Xcode
    #   uses: maxim-lobanov/setup-xcode@v1
    #   with:
    #     xcode-version: '14.2'

    - name: Install the Apple certificate and provisioning profile
      env:
        BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
        P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables
        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/MyChat.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode --output $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode --output $PP_PATH
        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        # import certificate to keychain
        security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH
        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Build IPA/iOS
      run: flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist
      # run: flutter build ios --release --no-codesign
    
    - name: Upload ipa artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-ipa
        path: ${{ env.PATH_TO_IPA }}
        retention-days: 2

    - name: Create App Store API key
      env:
        APP_STORE_CONNECT_API_PRIVATE_KEY_BASE64: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY_BASE64 }}
      run: |
        # create api private key 
        APP_STORE_CONNECT_API_PRIVATE_KEY=$RUNNER_TEMP/api-private-key.p8
        # import api private key from secrets
        echo -n "$APP_STORE_CONNECT_API_PRIVATE_KEY_BASE64" | base64 --decode --output $APP_STORE_CONNECT_API_PRIVATE_KEY

    - name: Deploy to App Store (Testflight)
      uses: apple-actions/upload-testflight-build@v1
      with:
        app-path: ${{ env.PATH_TO_IPA }}
        issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
        api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        api-private-key: $RUNNER_TEMP/api-private-key.p8

    - name: Clean up keychain and provisioning profile
      if: ${{ always() }}
      run: |
        security delete-keychain $RUNNER_TEMP/app-signing.keychain-db
        rm ~/Library/MobileDevice/Provisioning\ Profiles/MyChat.mobileprovision

    # - name: Build IPA
    #   env:
    #     FS_KEYCHAIN_PASS: ${{ secrets.FS_KEYCHAIN_PASS }}
    #   run: |
    #     echo "Unlocking keychain"
    #     security unlock-keychain -p "$FS_KEYCHAIN_PASS" ~/Library/Keychains/build.keychain
    #     # Important, just in case the build takes longer than the default 300s timeout
    #     # Otherwise the build will freeze at signing the frameworks if the keychain is locked
    #     echo "Increasing keychain auto lock timeout"
    #     security set-keychain-settings -lut 1800 ~/Library/Keychains/build.keychain
    #     flutter build ipa --release
    #     echo "Locking keychain"
    #     security lock-keychain ~/Library/Keychains/build.keychain
    # - name: Upload IPA artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: release-ipa
    #     path: ${{ env.PATH_TO_IPA }}
